/**
 * Google Chrome repeatedly asks for permission to access the microphone, unless
 * HTTPS is being used.  This slows down the speech recognition process, which
 * slows down the reaction time of the robot.
 *
 * This file sets off a HTTPS server, which avoids the aforementioned problem.
 * Chrome doesn't like the self signed certificate, but you don't have to worry
 * about that for the sake of this example.
 */
var express = require('express');
var netsocket = require('net').Socket();

var app = express();
var httpapp = express();
var fs = require('fs');

// SSL Requirements (generated by OpenSSL)
var options = {
    key: fs.readFileSync('cert/key.pem'),
    cert: fs.readFileSync('cert/cert.pem'),
    requestCert: true
};

var http = require('http').createServer(httpapp);
var server = require('https').createServer(options, app);
var io = require('socket.io').listen(server);

// Redirects all from HTTP to HTTPS
httpapp.get('*',function(req,res){
    res.redirect('https://127.0.0.1:8080'+req.url)
})

// Need this to serve the static files (i.e. images)
app.use(express.static(__dirname));

// Handles "GET" Requests
app.get('/', function(req, res){
  res.sendFile(__dirname+'/arduino-speech.html');
});


// Handles socket.io communication
io.on('connection', function(socket){
  socket.on('command', function(msg){

    console.log('command: ' + msg)

    // Sends command further to ardino module via TCP connection running on 9090
    netsocket.connect(9090);
    netsocket.write(msg);
    netsocket.end();

    //io.emit('command', msg);
  });
});

server.listen(8080);
http.listen(8081);
